server:
  port: 8081

services:
  user:
    url: ${USER_SERVICE_URL:http://localhost:8084}

auth:
  jwt:
    secret: ${AUTH_JWT_SECRET:contact-management-auth-secret-key-2026}
    expiry-seconds: ${AUTH_JWT_EXPIRY:3600}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

  instance:
    prefer-ip-address: true